<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_profil_lembaga_model extends CI_Model
{

    public $table = 'tbl_profil_lembaga';
    public $id = 'id_lembaga';
    //public $order = 'DESC';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_lembaga,nama_lembaga,alamat,provinsi,kabupaten,no_telpon,logo');
        $this->datatables->from('tbl_profil_lembaga');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_profil_lembaga.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('profillembaga/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('profillembaga/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor(site_url('profillembaga/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_lembaga');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_lembaga', $q);
	$this->db->or_like('nama_lembaga', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('no_telpon', $q);
	$this->db->or_like('logo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_lembaga', $q);
	$this->db->or_like('nama_lembaga', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('no_telpon', $q);
	$this->db->or_like('logo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_profil_lembaga_model.php */
/* Location: ./application/models/Tbl_profil_lembaga_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-08 01:42:17 */
/* http://harviacode.com */